/**
 * generated by Xtext 2.17.0
 */
package ic.ac.uk.xdrone.ui.labeling;

/**
 * Provides labels for IEObjectDescriptions and IResourceDescriptions.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#label-provider
 */
@SuppressWarnings("all")
public class XDroneDescriptionLabelProvider /* implements DefaultDescriptionLabelProvider  */{
}
