/**
 * generated by Xtext 2.17.0
 */
package ic.ac.uk.xdrone.ui.labeling;

/**
 * Provides labels for EObjects.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#label-provider
 */
@SuppressWarnings("all")
public class XDroneLabelProvider /* implements DefaultEObjectLabelProvider  */{
  /* @Inject
   */public XDroneLabelProvider(final /* AdapterFactoryLabelProvider */Object delegate) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method super(AdapterFactoryLabelProvider) is undefined");
  }
}
