/**
 * generated by Xtext 2.17.0
 */
package ic.ac.uk.xdrone.ui;

import ic.ac.uk.xdrone.ui.AbstractXDroneUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
/* @FinalFieldsConstructor */@SuppressWarnings("all")
public class XDroneUiModule extends AbstractXDroneUiModule {
}
