/**
 * generated by Xtext 2.17.0
 */
package ic.ac.uk.xdrone.ui.quickfix;

/**
 * Custom quickfixes.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
@SuppressWarnings("all")
public class XDroneQuickfixProvider /* implements DefaultQuickfixProvider  */{
}
